<?php
// List of banks in India from RBI
$banks = [
    "Allahabad Bank",
    "Andhra Bank",
    "Axis Bank",
    "Bank of Baroda",
    "Bank of India",
    "Bank of Maharashtra",
    "Canara Bank",
    "Central Bank of India",
    "City Union Bank",
    "Corporation Bank",
    "Cosmos Bank",
    "DCB Bank",
    "Dena Bank",
    "Deutsche Bank",
    "Dhanlaxmi Bank",
    "Federal Bank",
    "HDFC Bank",
    "HSBC Bank",
    "ICICI Bank",
    "IDBI Bank",
    "IDFC Bank",
    "Indian Bank",
    "Indian Overseas Bank",
    "IndusInd Bank",
    "Jammu & Kashmir Bank",
    "Karnataka Bank",
    "Karur Vysya Bank",
    "Kotak Mahindra Bank",
    "Lakshmi Vilas Bank",
    "Nainital Bank",
    "Oriental Bank of Commerce",
    "Punjab & Sind Bank",
    "Punjab National Bank",
    "RBL Bank",
    "Saraswat Bank",
    "South Indian Bank",
    "Standard Chartered Bank",
    "State Bank of India",
    "Syndicate Bank",
    "Tamilnad Mercantile Bank",
    "UCO Bank",
    "Union Bank of India",
    "United Bank of India",
    "Vijaya Bank",
    "Yes Bank",
    "Bandhan Bank",
    "Catholic Syrian Bank",
    "Citibank",
    "DBS Bank",
    "ESAF Small Finance Bank",
    "Equitas Small Finance Bank",
    "AU Small Finance Bank",
    "Jana Small Finance Bank",
    "North East Small Finance Bank",
    "Suryoday Small Finance Bank",
    "Ujjivan Small Finance Bank",
    "Utkarsh Small Finance Bank",
    "Paytm Payments Bank",
    "Airtel Payments Bank",
    "India Post Payments Bank",
    "Fino Payments Bank",
    "Jio Payments Bank"
];

// Sort banks alphabetically
sort($banks);
?>

